# Server settings (ServerProperties)
server:
    port: 9000
    servletPath: /uip

multipart:
    maxFileSize: 5Mb
    maxRequestSize: 10Mb

doc:
    inter:
        code: 100000000001
        basicParamPath: inter/param.json

mail:
    fromEmail: chenmm6@asiainfo.com
    fromPassword: arenagod@123
        
spring:
    datasource:
        url: jdbc:mysql://172.11.32.21:3306/uip
        username: ailife
        password: ailife
        continueOnError: false